timeout:
  task_timeout_s: 21600
  action_timeout_s: 3600
  command_timeout_s: 300
  dial_timeout_s: 5
ssh:
  port: 22
  pty:
    term: ""
    width: 80
    height: 60
    ispeed: 14400
    ospeed: 14400
    interval_ms: 100
  ciphers:
    - "aes128-ctr"
    - "aes192-ctr"
    - "aes256-ctr"
    - "aes128-gcm@openssh.com"
    - "arcfour256"
    - "arcfour128"
    - "aes128-cbc"
    - "3des-cbc"
    - "aes192-cbc"
    - "aes256-cbc"
cache:
  expiration_s: 900
  cleanup_interval_s: 10
  ticker_interval_s: 10
crypt:
  type: ""
  key: ""
output:
  type: "text"
  ordered: false
concurrency: 20
common_commands:
  - "date"
  - "pwd"
command_sep: ";"
